"""empty message

Revision ID: 094ae1c42197
Revises: ffdc0a98111c
Create Date: 2023-01-21 15:22:46.591353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094ae1c42197'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.String(length=10), nullable=False),
    sa.Column('review_body', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('pm_tagline', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_img', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('property_type', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('pm_rate', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('users', sa.Column('zipcode', sa.String(length=5), nullable=False))
    op.add_column('users', sa.Column('avg_rating', sa.String(length=3), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avg_rating')
    op.drop_column('users', 'zipcode')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'pm_rate')
    op.drop_column('users', 'property_type')
    op.drop_column('users', 'profile_img')
    op.drop_column('users', 'pm_tagline')
    op.drop_table('reviews')
    # ### end Alembic commands ###